"""Initial migration

Revision ID: 7f23e3c3daee
Revises: 
Create Date: 2025-03-04 22:51:13.791500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f23e3c3daee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_currency', table_name='prices')
    op.drop_index('ix_prices_id', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_withdrawals_id', table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index('ix_deposits_id', table_name='deposits')
    op.drop_index('ix_deposits_wallet_address', table_name='deposits')
    op.drop_table('deposits')
    op.drop_index('ix_current_prices_currency', table_name='current_prices')
    op.drop_index('ix_current_prices_id', table_name='current_prices')
    op.drop_table('current_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='current_prices_pkey')
    )
    op.create_index('ix_current_prices_id', 'current_prices', ['id'], unique=False)
    op.create_index('ix_current_prices_currency', 'current_prices', ['currency'], unique=True)
    op.create_table('deposits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='deposits_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deposits_pkey')
    )
    op.create_index('ix_deposits_wallet_address', 'deposits', ['wallet_address'], unique=True)
    op.create_index('ix_deposits_id', 'deposits', ['id'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='withdrawals_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='withdrawals_pkey')
    )
    op.create_index('ix_withdrawals_id', 'withdrawals', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('xrp_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('btc_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('usd_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='prices_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prices_pkey')
    )
    op.create_index('ix_prices_id', 'prices', ['id'], unique=False)
    op.create_index('ix_prices_currency', 'prices', ['currency'], unique=False)
    # ### end Alembic commands ###
